GRANT ALL PRIVILEGES ON `cmss`.* TO 'CMSS-PRE5'@'%' IDENTIFIED BY PASSWORD '*24CCE02EF76DC3288A33A1CBD7B9B4E4FCA6E628' WITH GRANT OPTION;


GRANT ALL PRIVILEGES ON `cmss`.* TO 'CMSS-PRE5'@'localhost' 

SET PASSWORD FOR 'CMSS-PRE5'@'%' = PASSWORD('パスワード'); ローカルホストと両方やった。
