GRANT ALL PRIVILEGES ON `cmss`.* TO 'CMSS-PRE5'@'%' IDENTIFIED BY PASSWORD '*24CCE02EF76DC3288A33A1CBD7B9B4E4FCA6E628' WITH GRANT OPTION;


GRANT ALL PRIVILEGES ON `cmss`.* TO 'CMSS-PRE5'@'localhost' 

SET PASSWORD FOR 'CMSS-PRE5'@'%' = PASSWORD('パスワード'); ローカルホストと両方やった。

CREATE USER 'CMSS_PRE6'@'%' IDENTIFIED VIA mysql_native_password USING 'TWC2g8FmmRdxLlqb';GRANT ALL PRIVILEGES ON *.* TO 'CMSS_PRE6'@'%' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON `cmss`.* TO 'CMSS_PRE6'@'%'; 
